spring.application.name=pomodorozion
server.port=${PORT:8080}
spring.main.banner-mode=off

pomodoro.duration=25
pomodoro.short-break=5
pomodoro.long-break=15

spring.datasource.url=jdbc:h2:file:./data/pomodorozion
spring.jpa.hibernate.ddl-auto=update